[package]
name = "simple-ecs-deploy-tool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
aws-config = "1.1.1"
aws-sdk-ecr = "1.15.0"
aws-sdk-ecs = "1.20.0"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1.77"
